#!/bin/sh
node hello_sqlite.js test1.db &
node hello_sqlite.js test2.db &
node hello_sqlite.js test3.db &
node hello_sqlite.js test4.db &
node hello_sqlite.js test5.db &
node hello_sqlite.js test6.db &
node hello_sqlite.js test7.db &
node hello_sqlite.js test8.db &
node hello_sqlite.js test9.db &
node hello_sqlite.js test10.db &
node hello_sqlite.js test11.db &
node hello_sqlite.js test12.db &
node hello_sqlite.js test13.db &
node hello_sqlite.js test14.db &
node hello_sqlite.js test15.db &
node hello_sqlite.js test16.db &
node hello_sqlite.js test17.db &
node hello_sqlite.js test18.db &
node hello_sqlite.js test19.db &
node hello_sqlite.js test20.db &
